apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ploclo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kansumware/backend:latest
          command: ["sh", "-c", "until nc -z postgres 5432; do echo Waiting...; sleep 2; done && echo Postgres ready! && npx prisma db push && node dist/index.js"]
          envFrom:
            - secretRef:
                name: ploclo-secret
          ports:
            - containerPort: 3001
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5