apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ploclo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kansumware/frontend:latest
          envFrom:
            - secretRef:
                name: ploclo-secret
          ports:
            - containerPort: 3000
              targetPort: 3000
              nodePort: 30000