apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ploclo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:           
        - name: registry-secret
      containers:
        - name: frontend
          image: 104.197.255.217:5000/frontend:latest
          envFrom:
            - secretRef:
                name: ploclo-secret
          ports:
            - containerPort: 3000