apiVersion: v1
kind: Secret
metadata:
 name: ploclo-Secret
 namespace: ploclo
type: Opaue
stringData:
  DB_HOST=postgres
  DB_PORT= "5432"
  DB_USER= postgres
  DB_PASSWORD= admin123
  DB_NAME= myapp
  JWT_SECRET= "B1]4e']Bd;G#(O[eFS$+NBl,E~P}UFDSS@,-wr$(1=jD^zj^#i"

  DATABASE_URL= "postgresql://postgres:admin123@postgres:5432/myapp?schema=public"

  GOOGLE_CLIENT_ID= 392597748306-iu8fgom6d6jgq9lm47hrpekahco7ha0a.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET= 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
  GOOGLE_CALLBACK_URL= http://104.197.255.217:8000/api/auth/google/callback

  NODE_ENV= development
  NEXT_PUBLIC_API_URL= http://104.197.255.217:8000/api
