name: workflow-tmas-scan

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: CheckOut
              uses: actions/checkout@v4

            - name: Build Docker Images
              run: |
               docker compose build

            - name: Show docker Images
              run: docker images

            - name: Download TMAS
              run: |
               curl -L -o tmas.tar.gz https://ast-cli.xdr.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz
               tar -xzf tmas.tar.gz
               chmod +x ./tmas

            - name: Verify TMAS
              run: |
               ./tmas --version
            
            - name: Scan Backend Image
              run: |
               ./tmas scan \
               --artifact ploclo_cms-main_backend \
               --token ${{ secrets.VISION_ONE_API_KEY }}

            - name: Scan frontend Image
              run: |
               ./tmas scan \
               --artifact ploclo_cms-main_frontend \
               --token ${{ secrets.VISION_ONE_API_KEY }}
