// layout.tsx
import { Kanit } from "next/font/google";
import "./globals.css";
import I18nProvider from "../i18nProvider";
import ClientWrapper from "../components/ClientWrapper";
import { AuthProvider } from "./context/AuthContext";
// 1. Import the Provider
import { GoogleOAuthProvider } from "@react-oauth/google";
import { ToastProvider } from "@/app/context/ToastContext";

const kanit = Kanit({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin", "thai"],
  variable: "--font-kanit",
  display: "swap",
});

export const metadata = {
  title: "PLOCLO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${kanit.variable} font-kanit antialiased`}>
        {/* 2. Wrap everything with your Client ID */}
        <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID || ""}>
          <AuthProvider>
            <I18nProvider>
              <ClientWrapper>
                <ToastProvider>{children}</ToastProvider>
              </ClientWrapper>
              {/* Footer Info (Optional) */}
              <footer className="text-center text-slate-400 text-xs pb-4 ml-[200px]">
                © 2026 PLOCLO Management System • All Rights Reserved
              </footer>
            </I18nProvider>
          </AuthProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
