name: docker-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull images
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ploclo_cms-main-backend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ploclo_cms-main-frontend:latest

      - name: Create network
        run: docker network create myapp-net || true

      - name: Stop old containers
        run: |
          docker stop postgres || true
          docker rm postgres || true
          docker stop backend || true
          docker rm backend || true
          docker stop frontend || true
          docker rm frontend || true

      - name: Run postgres
        run: |
          docker run -d \
            --name postgres \
            --network myapp-net \
            -e POSTGRES_PASSWORD=admin123 \
            -e POSTGRES_DB=myapp \
            postgres:15

      - name: Run backend
        run: |
          docker run -d \
            --name backend \
            --network myapp-net \
            -p 9771:9771 \
            -e DATABASE_URL="postgresql://postgres:admin123@postgres:5432/myapp" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            ${{ secrets.DOCKERHUB_USERNAME }}/ploclo_cms-main-backend:latest

      - name: Run frontend
        run: |
          docker run -d \
            --name frontend \
            --network myapp-net \
            -p 3000:3000 \
            -e NEXT_PUBLIC_API_URL="http://104.197.255.217:9771/api" \
            ${{ secrets.DOCKERHUB_USERNAME }}/ploclo_cms-main-frontend:latest
  
         # - name: Scan Backend Image
            #   uses: trendmicro/tmas-scan-action@v3.1.0
            #   with:
            #      version: 'latest'
            #      vulnerabilitiesScan: true
            #      malwareScan: false
            #      artifact: registry:${{ secrets.DOCKERHUB_USERNAME }}/ploclo_cms-main-backend:latest
            #      additionalArgs: --region=ap-southeast-1
            #      tmasApiKey: ${{ secrets.VISION_ONE_API_KEY }}
            #      githubToken: ${{ secrets.GITHUB_TOKEN }}

            # - name: Scan Frontend Image
            #   uses: trendmicro/tmas-scan-action@v3.1.0
            #   with:
            #    version: 'latest'
            #    vulnerabilitiesScan: true
            #    malwareScan: false
            #    artifact: registry:${{ secrets.DOCKERHUB_USERNAME }}/ploclo_cms-main-frontend:latest
            #    additionalArgs: --region=ap-southeast-1
            #    tmasApiKey: ${{ secrets.VISION_ONE_API_KEY }}
            #    githubToken: ${{ secrets.GITHUB_TOKEN }}


    # deploy:
    #    runs-on: self-hosted
    #    needs: TMAS-SCAN
    #    steps:

    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #           with:
    #            submodules: true

    #         - name: Check minikube Status
    #           run: |
    #            minikube status
    #            kubectl cluster-info

    #         - name: Clean Minikube Disk
    #           run: |
    #            minikube ssh -- docker system prune -af || true

    #         - name: Pull images
    #           run: |
    #            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ploclo_cms-main-frontend:latest
    #            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ploclo_cms-main-backend:latest

    #         - name: Apply manifests & Deploy to minikube
    #           run: |
    #            MINIKUBE_IP=$(minikube ip)

    #            sed -i "s|MINIKUBE_IP_PLACEHOLDER|http://${MINIKUBE_IP}:30000|g" \
    #            PLOCLO_cms-main/k8s/frontend-deployment.yaml

    #            kubectl apply -f PLOCLO_cms-main/k8s/postgres-deployment.yaml
    #            kubectl apply -f PLOCLO_cms-main/k8s/backend-deployment.yaml
    #            kubectl apply -f PLOCLO_cms-main/k8s/frontend-deployment.yaml

    #            kubectl set image deployment/frontend \
    #            frontend=${{ secrets.DOCKERHUB_USERNAME }}/ploclo_cms-main-frontend:latest

    #            kubectl set image deployment/backend \
    #            backend=${{ secrets.DOCKERHUB_USERNAME }}/ploclo_cms-main-backend:latest

    #            kubectl rollout status deployment/frontend
    #            kubectl rollout status deployment/backend
          

            # - name: Download TMAS
            #   run: |
            #    curl -L -o tmas.tar.gz https://ast-cli.xdr.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz
            #    tar -xzf tmas.tar.gz
            #    chmod +x ./tmas

            # - name: Verify TMAS
            #   run: |
            #    ./tmas --version
            
            # - name: Scan Backend Image
            #   run: |
            #    ./tmas scan image ploclo_cms-main-backend:latest \
            #    --token {{ secrets.VISION_ONE_API_KEY }}

            # - name: Scan frontend Image
            #   run: |
            #    ./tmas scan image ploclo_cms-main-frontend:latest \
            #    --token {{ secrets.VISION_ONE_API_KEY }}
