name: K8s Deployment

on:
  push:
    branches:
      - kan-ploclo

jobs:
  CI-git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Clean Docker Image
        run: |
         docker image prune -a -f

  CD-Deploy:
     needs: CI-git
     runs-on: self-hosted

     steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push Backend
        run: |
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest ./PLOCLO_cms/backend
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Build and Push Frontend
        run: |
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./PLOCLO_cms/frontend
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Deploy to K8s
        run: |
          kubectl apply -f ./PLOCLO_cmsk8s/namespace.yaml
          kubectl apply -f ./PLOCLO_cmsk8s/k8s/secret.yaml
          kubectl apply -f ./PLOCLO_cmsk8s/k8s/postgres/
          kubectl apply -f ./PLOCLO_cmsk8s/k8s/backend/
          kubectl apply -f ./PLOCLO_cmsk8s/k8s/frontend/

      - name: Rollout restart (pull latest image)
        run: |
          kubectl rollout restart deployment/backend -n ploclo
          kubectl rollout restart deployment/frontend -n ploclo

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/backend -n ploclo --timeout=120s
          kubectl rollout status deployment/frontend -n ploclo --timeout=120s





































      # - name: Create .env file
      #   working-directory: ./PLOCLO_cms
      #   run: |
      #    echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
      #    echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
      #    echo "DB_USER=${{ secrets.DB_USER }}" >> .env
      #    echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
      #    echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
      #    echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
      #    echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      #    echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
      #    echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
      #    echo "GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}" >> .env
      #    echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
      #    echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env

      # - name: Deploy with docker compose
      #   working-directory: ./PLOCLO_cms
      #   run: |
      #    docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
      #    docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
      #    docker compose up -d --build

      